- name: Install Git
  ansible.builtin.apt:
    name: git
    state: latest
  when: ansible_facts['os_family'] == "Debian"
  become: true

- name: Write gitconfig file for sudoers users
  ansible.builtin.copy:
    src: ./tools-cli/git/gitconfig
    dest: "/home/{{ item }}/.gitconfig"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0644'
  with_items: "{{ sudoers }}"
  when: ansible_facts['os_family'] == "Debian"
  become: true
