- name: Install NeoVim
  ansible.builtin.apt:
    name: neovim
    state: latest
  when: ansible_facts['os_family'] == "Debian"
  become: true

- name: Write Neovim Configs
  ansible.builtin.copy:
    src: ./tools-cli/neovim/
    dest: ~/.config/nvim/
  become: true
  become_user: developer

