- name: Install Zsh
  ansible.builtin.apt:
    name: zsh
    state: latest
  when: ansible_facts['os_family'] == "Debian"
  become: true

- name: Set Zsh as default shell for sudoers users
  ansible.builtin.user:
    name: "{{ item }}"
    shell: /usr/bin/zsh
  with_items: "{{ sudoers }}"
  when: ansible_facts['os_family'] == "Debian"
  become: true

# Dynamically assemble .zshrc from all tool-specific fragments
# Each tool in tools-cli/ can provide its own .zshrc file with tool-specific
# config/aliases. This task finds all .zshrc files and concatenates them into
# the user's ~/.zshrc. No need to manually update this when adding new tools.
- name: Find all .zshrc fragments
  ansible.builtin.find:
    paths: "{{ playbook_dir }}/tools-cli"
    patterns: "*.zshrc"
    recurse: yes
    file_type: file
    hidden: yes
  register: zshrc_fragments
  delegate_to: localhost
  run_once: true
  when: ansible_facts['os_family'] == "Debian"

- name: Assemble .zshrc from fragments for sudoers users
  ansible.builtin.copy:
    content: |
      {% for fragment in zshrc_fragments.files | sort(attribute='path') %}
      {{ lookup('file', fragment.path) }}

      {% endfor %}
    dest: "/home/{{ item }}/.zshrc"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: '0644'
  with_items: "{{ sudoers }}"
  when:
    - ansible_facts['os_family'] == "Debian"
    - zshrc_fragments.files | length > 0
  become: true
